DEBUG    logger:test_cases.py:37 响应结果：